version: "~> 1.0"
os: linux
language: shell
services: docker
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    if: branch = master
    rooms:
      secure: IvPxboLCvxBJVwd+yLAzA2eACO/NhD+E1i2p6EljzPNx//gaHJM0AX4P1JZq8sTZ+NSaSWX9KZeZXqQFtOYjQAbg4RszFq8gxGPCdDHPyDz+IPPW3QlsEGupEy1lB14xO08tA7o4/Q92jIJ35nXJr0nzvFKinzn+C8M6wQUzLHHo82kw1kI9BjJyy40zJC6QJAn8qan7NsJ2qIUqRSXV9uO5+J0R5feRoWMqj33WJbTHEsQP9B022iC7lULbSkJujW4pCr6ZmPaz2FVzS0Gm9RhlY/aS+LUfzC6gCPyASsDFALrI9xBPqbjse6cYIAyQdOw6PeD78nBLy9FkdSy5IIc1JwXm6cgKlquNfXSm636kZKiFsX/aDmEJkFo/QLDSOg6IbrGJY3NMLGFsyq1atj8kvdTlJHtgo6POnH51nczeF23Tun13RjYNpNWcDAjwe9yBvGJl8VUtVBeVvrYgkWEw2ULHafIUGXlkuL8LYxknov5s1hsz7/Fxx68k3c+av892PE98lUlhc1HcrO79J/S7izUzwKlngCJUCrF7EZBycrbJ2vWzPOwyWNQqkMgON6EAWj8memROSNL25fAyZ2rWefD8pZzJYUNmEdekd99jcHFSpGftUcfhzcv9OVjsQojuT2iQf4swd3gOEc8eYEK7m3hP2TedFtRA/CQgBBE=
    template:
    - "%{commit_subject}"
    - build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) @%{branch}
    - by %{author} %{result} in %{duration}
    on_success: change
    on_failure: always
env:
  global:
  - secure: kA+c+hJFnVfEqjPYJ/ktugbpklJzduLBuJsPYgOE//IluBz3LVl0VLmrbJEE8qCbcGA7jNFXZydHG2I/VcflowlatQ0PR6PkV3hJxIHbVEmQYEPVGD9NmRRVLr+U7Cw24sqMjnlyc00egWLHXNboWSEJj4p+1c4XY6SmBBnhO5Cwkg7KmLnZya82zpjWxy7xYgcVJEOhiz3LSaGxy9N21zpt4RGU1VM1E+ULjuNyi3s6lFcfYqMuAdbl8xWoBrHDP6ZSzaHji4hoexvK8VRkJ7yps+6JpDuVUrZuNGKDe4qIjqOSScm57LlJOMc6bK830OO2RdOyx2nggCHZlqakuGIGaCHHInKEIDl4aFyoOY7wk+ftclA4gope1eK/ew6Op3Uwm17K20Fk49waWV//FwItP50f+zf0pVgyXG/T/RjVkT1bEGc6fWVzGQXaPhv1556sC7Mp1q2G8buQomg7QdvaP2/X0JLFQslOfe31kER9WfYJCtjP6gUtzwr+zg1eE9hcFPiYoByToBiyk0vzv4ZaIFsPpngwc+tZuP0iFFL366LmiD/hWDjlJRQGqKB7jpTpp6n+unxgsBJ98tNG6IMQR0Q4zrXlyUN8scPPhfbx8E88IQvYD8jyFi3x4KAg8Hp7vnRrBGkK2v/b4ZTCgURlBfc0IcUl4VcTEF1I/JU=
  - secure: qGcN2e3z/RgCoEnrsLL8CMdafn3sso5TJImVEQTQK93bA+Bfda1m+2S0oU0ZTnBGNMjVnIH9DjtCc8iGeelZBM0/1dhi0CRWVVl6un/q13dceq+W0T2V5j6ge0ECJDWPIj8oQiPLNVa4oTlk2Aw+Q4tFqeWotSSaeSCPANU0fDH/TYhBXdVt0R6GcM7n8oY8d4F6/amMdPu7VzYkpwWAXRdS6xIDmiRcB1nOZJ00qM+N+UdR6lIFX/ZxpMHnjJlMMvQHbaBu3Z3Uv9Rnvl+0bO0GdCQesxtrckaO3uqMaP6mp2ikmZGotXuH2UzAL8ROQDred/lUSOS7bZ1AVQe5g/dA3/uuR3qUsG3TDUvz0Ij/IflwvlfJmyER/0hPIfBCvSK7nnoFNBHmOqr37HT4Hd2+5Ogd42yPhZsBZJltqmLGpCtLPDEwKnSDYwSOVrpI10w/V6gs+CL+ndrZXP5J/X6iHsRU0DMxZt96XaPEIkqxz21DvNxqSeWT0Qr/ikiOewUfJwoLiy431pjN3eb15gOUbxr302OQIJy3zaxIE7ZDJ/2LzkmSaR0QjTGHdE0AC3v1bAPVUBGD2Ie+Jt3YGMlyxXaBwPV+lAFy3Voq0KcC98Rj9dHtsYNCpYE433Pl2Nk1nug7COiU9YuyX3JgjCJaljdjxcCSnHu2Eg3rAUI=
  - secure: cTYJ5LZtjOPxWRInHwXK/NetVF+EhpSGB+VaIIUCZZ7Jw9hg88qwHmdPQO6Iv9BmQwAaNcoob6vtIuNnTwgH4houPdvRQU5EFaAnlAe0zXn2EOVYiX0hJBLqKa1LMkwM+axI82VjjGXT7yDYVB49nLxKwxqYp/O/xbnVQcHuNyd2qHc5tJAo1EnbsVSGP0sWkHxtYtsFRIHkWsjbkb/ADN8vm+Sq54KAtwXDz1mhvaO49nJj2lv7JrYnLN/VX9lDo4MCZ9/sxnLHLeANZ7FbCA+ObbXqEd4qDeBhj3cVq/ywHvOkesHNqyoe22FfojpPx3m93DWHV9uE3L1U6xQaNflLvlTLuDcPA3nB4WGWxLGbxLAZt8vECeCbTcJRTW6wnzb6rKxJfkJMfUqDW5wQ1vspS0x3yIy+nd44JB+EGkOUMegiYgX5i9FlPP8qOXz7riWZJ+4UA/Dnzlsz/e8FgIy4v+vCdP2flUDywcdVz64Q65JNDABjA/Eox/eb55DjLnkCOQ6GtE93jH2QVHbzGnSuhXzk+wFrnEW5X2vV03EwXSINAt6VowTFPkCM/sO4HHz8EleoVVl5HW9A4QT9AgEy79BSO3AcJY6qZ5s91FYtclkOXx+GE9LxRvgCF2afwtX26/sWb0QkfS2y5uIPAj2aQrskdg02NE57DdnBqd8=
before_install: curl -sSL https://raw.githubusercontent.com/ckaserer/bash-script-collection/master/bash-fetch-script-collection.sh | bash
script: .ci/test.sh
deploy:
  provider: script
  script: bash bash-script-collection/docker-push-image.sh \
            --docker-org  ckaserer \
            --docker-repo travis-cli \
            --docker-user ${DOCKER_USER} \
            --docker-pass ${DOCKER_PASS}
  skip_cleanup: true
  on:
    branch: master
