#!/bin/bash

readonly TOPLEVEL_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && cd .. && pwd )
for functionFile in ${TOPLEVEL_DIR}/functions/*.sh;do source ${functionFile}; done

prefix="DOCKER"
username=${2}

echo -n Password: 
read -s password
echo

travis_encrypt_key_value "env.global" "${prefix}_USER" "${username}" 
travis_encrypt_key_value "env.global" "${prefix}_PASS" "${password}" 